### ISSUE TITLE
Build fails on linux-mint / Debian

### ISSUE THREAD

**Issue by demerphq** [wbraswell/alien-pcre2#16]
I am trying to resolve https://github.com/Perl/perl5/issues/20710 for re-engine-PCRE2, which depends on this module.

Currently it does not build on Debian under blead perl. I do not think it is because of blead however, I think the name of the library may have changed. I see libpcre-2-8-0 but not libpcre-2-8

I am at loss as how to proceed on this. I am not familiar with the Alien framework at all.

**Comment by zmughal** [comment]
As on IRC, Alien::Base packages support two different ways of installation:

- system: uses whatever is available on the user's system. In the case of Alien::PCRE2, probes for this by using `pkg-config`. On Debian-based systems, this requires the package `libpcre2-dev`, not just the library package `libpcre2-8-0`.

- share: this installs into a share dir. In the case of Alien::PCRE2, this downloads from GitHub, but as @plicease pointed out in IRC, the version on CPAN is currently broken because of a change in the GitHub releases page. The fix for this has already been applied in #15, but isn't on CPAN yet.

**Comment by wbraswell** [comment]
Howdy @demerphq , we just released a new version 0.017 on CPAN, can you please check if it fixes all your current issues including this issue #16?
https://metacpan.org/release/WBRASWELL/Alien-PCRE2-0.017000

**Comment by demerphq** [comment]
Sure, I'm a bit busy today with family obligations, but I'll check it out
ASAP.

Thanks for the update!

Yves

**Comment by demerphq** [comment]
LGTM.

```
Configuring Alien-PCRE2-0.017000 ... OK
Building and testing Alien-PCRE2-0.017000 ... OK
Successfully installed Alien-PCRE2-0.017000
```
Seems to be fixed to me.

**Comment by demerphq** [comment]
Thanks!

**Comment by wbraswell** [comment]
Great, thanks @demerphq !  :-)
